export type Condition =
  | "adhd"
  | "asd"
  | "dyslexia"
  | "dyscalculia"
  | "anxiety"
  | "depression"
  | "default";

export const themes: Record<Condition, Record<string, string>> = {
  default: {
    "--color-bg": "#F8F9FA",
    "--color-surface": "#FFFFFF",
    "--color-primary": "#2C3E50",
    "--color-accent": "#6FA8DC",
    "--color-highlight": "#A7C7E7",
    "--color-text": "#1F2933",
    "--color-text-muted": "#5B6B7A",
    "--color-success": "#4E8FC4",
    "--color-error": "#E74C3C",
    "--color-border": "#DEE4E8",
    "--border-radius": "8px",
    "--font-size-base": "15px",
    "--spacing-base": "1rem",
  },
  adhd: {
    "--color-bg": "#F4F6F8",
    "--color-surface": "#FFFFFF",
    "--color-primary": "#2C3E50",
    "--color-accent": "#6FA8DC",
    "--color-highlight": "#54C3EF",
    "--color-text": "#1F2933",
    "--color-text-muted": "#5F6F80",
    "--color-success": "#4EA78F",
    "--color-error": "#E74C3C",
    "--color-border": "#DDE1E5",
    "--border-radius": "8px",
    "--font-size-base": "15px",
    "--spacing-base": "1rem",
  },
  asd: {
    "--color-bg": "#F0F2EF",
    "--color-surface": "#F7F8F5",
    "--color-primary": "#4A5E52",
    "--color-accent": "#7A9E87",
    "--color-highlight": "#C4A882",
    "--color-text": "#2F3B35",
    "--color-text-muted": "#7A8C82",
    "--color-success": "#7A9E87",
    "--color-error": "#B07070",
    "--color-border": "#D8DDD8",
    "--border-radius": "6px",
    "--font-size-base": "15px",
    "--spacing-base": "1.4rem",
  },
  dyslexia: {
    "--color-bg": "#FFFDD0",
    "--color-surface": "#FFFBE3",
    "--color-primary": "#3F5668",
    "--color-accent": "#6E9CC0",
    "--color-highlight": "#E6B87A",
    "--color-text": "#2F3A3F",
    "--color-text-muted": "#5D676C",
    "--color-success": "#6AA48A",
    "--color-error": "#CC4444",
    "--color-border": "#E9E2B7",
    "--border-radius": "8px",
    "--font-size-base": "18px",
    "--spacing-base": "1.4rem",
  },
  dyscalculia: {
    "--color-bg": "#FFF4E8",
    "--color-surface": "#FFF9F0",
    "--color-primary": "#5A6F7E",
    "--color-accent": "#D9935E",
    "--color-highlight": "#E8B27A",
    "--color-text": "#2F3A3F",
    "--color-text-muted": "#756A5F",
    "--color-success": "#76A989",
    "--color-error": "#D05050",
    "--color-border": "#F0DDCD",
    "--border-radius": "12px",
    "--font-size-base": "17px",
    "--spacing-base": "1.5rem",
  },
  anxiety: {
    "--color-bg": "#F1F3FF",
    "--color-surface": "#FCFCFF",
    "--color-primary": "#5A6FB2",
    "--color-accent": "#B1B8E8",
    "--color-highlight": "#E6E6FA",
    "--color-text": "#2D3556",
    "--color-text-muted": "#7A82A8",
    "--color-success": "#87BFA2",
    "--color-error": "#B07080",
    "--color-border": "#DEE1F3",
    "--border-radius": "14px",
    "--font-size-base": "15px",
    "--spacing-base": "1.3rem",
  },
  depression: {
    "--color-bg": "#FFFAF2",
    "--color-surface": "#FFFFFF",
    "--color-primary": "#5C4A2A",
    "--color-accent": "#E8B86D",
    "--color-highlight": "#F4A460",
    "--color-text": "#3A2E1E",
    "--color-text-muted": "#907A60",
    "--color-success": "#80AE70",
    "--color-error": "#C07060",
    "--color-border": "#EDE0CC",
    "--border-radius": "12px",
    "--font-size-base": "15px",
    "--spacing-base": "1.2rem",
  },
};
